### ISSUE TITLE
Extract video from Vimeo API Request?

### ISSUE THREAD

**Issue by Cortlandd** [ed-george/AndroidVimeoExtractor#7]
Can the library extract video from an API request done through the Vimeo Java Networking API
i.e.
```java
String uri = ...; // obtained using one of the above methods
VimeoClient.getInstance().fetchNetworkContent(uri, new ModelCallback<VideoList>(VideoList.class) {
     @Override
     public void success(VideoList videoList) {
          if (videoList != null && videoList.data != null && !videoList.data.isEmpty()) {
               Video video = videoList.data.get(0); // just an example of getting the first video (Vimeo)
          }
     }

     @Override
     public void failure(VimeoError error) {
          // voice the error
     }
});
```

Can I ```getStream()``` from the  results of a request done through here? If so...any suggestions on how to approach.

I'm currently building an app, and because I don't have vimeo pro, I have to embed videos. I'm able to get the ```html: iframe``` link from under ```embed``` in the json response, and apply it to a WebView. But it won't work or play in the phone because mobile phones now don't support flash. Any suggestions on going about that? Also, if you'd like me to reexplain that, I can.

**Comment by ed-george** [comment]
If Vimeo's Video object contains a reference to its identifier or public vimeo url, you can use this library to extract the stream links - See the README on how to complete this.

From what I can see - the Video object returned contains variables named `resourceKey`, `uri` and `link` that _might_ contain the information this library would require in order to extract information.

I am closing this issue as it does not relate to a problem with this library - but feel free to contact me on twitter @edgeorge92 or email me if you require any further advice.
